# nacos 地址
url = "http://nacos-new-base-poc.cfuture.shop"

# nacos的命名空间名称
tenant = "application"

# 要替换的原配置
srcConfigString = "&autoconnect=true&"

# 替换之后的目标配置
targetConfigString = "&autoReconnect=true&"




