# nacos 地址
url = "http://nacos-zslnyy.cfuture.shop"

# nacos的命名空间名称
tenant = "cache"

# 要替换的原配置
srcConfigString = "host: redis-master.databases.svc.cluster.local"

# 替换之后的目标配置
targetConfigString = "sentinel:\n        master: mymaster\n        nodes: rfs-redisfailover.databases.svc.cluster.local:26379"



